### ISSUE TITLE
Vapor dependencies

### ISSUE THREAD

**Issue by CocoaPriest** [JustinM1/S3SignerAWS#11]
It's not very clean to use it in other frameworks like perfect, because of the Vapor dependencies. Isn't it possible to use some 3rd party lib like [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift)?

**Comment by JustinM1** [comment]
It's possible, but then it would require adding CryptoSwift to Vapor projects which already use the Vapor dependencies. So if you look at it from the perspective of someone using Vapor, adding CryptoSwift wouldn't be very clean. 

With that in mind I don't plan on making any changes regarding dependencies. However, it wouldn't be that bad to fork the repo and switch Vapor Crypto with CryptoSwift. it's mostly changing the HMAC syntax. If you decide to fork it I'll be happy to help if you run into any issues. I'll also add a link in the README for anyone who would like a version using CryptoSwift.
