### ISSUE TITLE
Invalid date format for signed delete request

### ISSUE THREAD

**Issue by ksmandersen** [JustinM1/S3SignerAWS#12]
I am getting the following error from Amazon when generating a v4 signed url for a delete request:
```
Optional(Response
- Version: 1.1.0
- Status: 400
- Headers:
	Connection: close
	Transfer-Encoding: chunked
	Server: AmazonS3
	x-amz-id-2: !REDACTED!
	x-amz-request-id: B14FD676248BDE17
	Content-Type: application/xml
	Date: Fri, 15 Sep 2017 13:35:43 GMT
- Body:
	<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationQueryParametersError</Code><Message>X-Amz-Date must be in the ISO8601 Long Format "yyyyMMdd'T'HHmmss'Z'"</Message><RequestId>B14FD676248BDE17</RequestId><HostId>WT6L5j7KbXwRLZAUvoqpZhFvpdl7QrnSA3E0aBEAOcMY5hb2ZXj74Uaug7Isf6oJHESZ/dT/oV0=</HostId></Error>)
```

I am generating the url like this:
```swift
return try signer.presignedURLV4(httpMethod: .delete, urlString: url,
                                         expiration: .thirtyMinutes, headers: [:])
```

**Comment by JustinM1** [comment]
hmm.. that's weird.  The formatter has this format:
    
      formatter.dateFormat = "yyyyMMdd'T'HHmmss'Z'"

And the current tests are passing against this V4 URL:

      "https://examplebucket.s3.amazonaws.com/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2Fus-east-1%2Fs3%2Faws4_request&
    X-Amz-Date=20130524T000000Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=aeeed9bbccd4d02ee5c0109b86d86835f995330da4c265957d157751f604d404"

Would you mind posting what the X-Amz-Date looks like in the v4 url causing the bad response?

**Comment by ksmandersen** [comment]
it looks like this ``X-Amz-Date=20170915T134944Z``

**Comment by ksmandersen** [comment]
I tried again and got this error:
```
Error><Code>AuthorizationQueryParametersError</Code><Message>Invalid credential date "20170915T134944Z". This date is not the same as X-Amz-Date: "20170915".</Message><RequestId>6BF1A2C47D2FE10A</RequestId><HostId>gsqfL4xkhW8V3T6gCh9PKzYlrcUnRD942ZT6r2eyUjic4AorJI+ATfgdEEiANuoVJc8MPqotd+0=</HostId></Error>
```

**Comment by JustinM1** [comment]
Alright, I'll get a project up and running today and see what I can figure out. I haven't integrated the updated version into my own projects yet.

**Comment by ksmandersen** [comment]
Sound great. Let me know if I can be of any help

**Comment by JustinM1** [comment]
I was able to get valid responses on `GET` and `DELETE` requests using pre-signed urls 
Here is a sample response received on a get request.

    Response
    - Version: 1.1.0
    - Status: 200
    - Headers:
	    Last-Modified: Tue, 16 May 2017 03:47:45 GMT
	    Accept-Ranges: bytes
	   ETag: "f9141d2473654f7adac5186079b4791f"
	   Server: AmazonS3
	   x-amz-id-2: 
	   x-amz-request-id: 
	  Date: Fri, 15 Sep 2017 16:41:00 GMT
	  Content-Type: binary/octet-stream
	  Content-Length: 819922

**Comment by ksmandersen** [comment]
Oh man, I took a closer look and figured out that this particular error occurs when trying to delete an object for a key that does not exist. The error is error message is really obscure though. 

Sorry for wasting your time on this.
