### ISSUE TITLE
Issue when compiling under Swift 4?

### ISSUE THREAD

**Issue by TempaGoGo** [JustinM1/S3SignerAWS#13]
Guys, When I try to complete a project under Swift 4, using S3SignerAWS, Xcode suggests a code change in the following function:

	internal func canonicalHeaders(
		headers: [String: String])
		-> String
	{
			let headerList = Array(headers.keys)
				.map { "\($0.lowercased()):\(headers[$0]!)" }
				.filter { $0 != "authorization" }
				.sorted { $0.localizedCompare($1) == ComparisonResult.orderedAscending }
				.joined(separator: "\n")
				.appending("\n")
			
			return headerList
}

to 

internal func canonicalHeaders(
		headers: [String: String])
		-> String
	{
			let headerList = Array(headers.keys)
				.map { "\($0.lowercased()):\(headers[$0]!)" }
				.filter { $0 != "authorization" }
				.sorted { $0.0.localizedCompare($0.1) == ComparisonResult.orderedAscending }
				.joined(separator: "\n")
				.appending("\n")
			
			return headerList
	}

This then causes other syntax issues.

Kind regards, Phil

**Comment by JustinM1** [comment]
Hey Phil,

Just updated project for swift 4 compatibility. You should be good to go.

Justin

**Comment by TempaGoGo** [comment]
Super - Thanks Justin! Phil
